# Generated by Django 4.0.3 on 2022-03-25 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catecategoria_libro', to='libro.categoria'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='portado',
            field=models.ImageField(blank=True, upload_to='portada'),
        ),
    ]
