# Generated by Django 4.0.3 on 2022-03-29 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0003_libro_stok_alter_libro_categoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='portado',
            new_name='portada',
        ),
    ]
