# Generated by Django 4.0.3 on 2022-03-25 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lector', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lector',
            name='apellidos',
            field=models.CharField(max_length=50, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='lector',
            name='nacionalidad',
            field=models.CharField(max_length=20, verbose_name='Nacionalidad'),
        ),
        migrations.AlterField(
            model_name='lector',
            name='nombres',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
    ]
